# Use the official Memcached image as the base image
FROM memcached:latest

# Optionally, you can add custom configuration files or scripts
# COPY ./config /path/to/config/
# COPY ./scripts /path/to/scripts/

# Expose the Memcached port
EXPOSE 11211
